/**
 * File: slug-entity.ts
 * Project: nuevo-dercomaq-api
 * File Created: Thursday, 28th February 2019 12:02:03 pm
 * Author: Felipe Rojos Almuna (felipe@inventures.cl)
 * -----
 * Last Modified: Tuesday, 26th March 2019 10:51:27 am
 * Modified By: Felipe Rojos Almuna (felipe@inventures.cl)
 * -----
 * Copyright 2019 - 2019 Incrementa Ventures SpA. ALL RIGHTS RESERVED
 * Terms and conditions defined in license.txt
 * -----
 * Inventures - www.inventures.cl
 */

 import {property} from '@loopback/repository';
 import {TimestampEntity} from './timestamp-entity';
 /**
  * Custom Entity that adds 3 properties:
  * Slug: The autogenerated string. Use for SEO
  * Name: String required for slug creation
  * Brand: String required for slug creation
  */
 export class SlugEntityTitle extends TimestampEntity {
   @property({
     type: 'string',
     description: 'Slug for ease-of-routing for the object',
   })
   slug: string;
 
   @property.array(String)
   slug_history?: string[];
 
   @property({
     type: 'string',
     required: true,
     description: 'New´s title',
   })
   title: string;
 }
 