name: LoopBack 4 deployment.

on:
  push:
    branches: ["dev", "devtechnew", "dev2", "fbdemo", "Atom-F0.3", "Atom-F0.4", "Atom-F0.5", "prodtech"]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "npm"

      - name: Install dependencies and build
        run: npm ci && npm run build

      - name: Install SSH Key and known_hosts
        uses: shimataro/ssh-key-action@v2.5.1
        with:
          key: ${{ secrets.FBDEVTECH_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.FBDEVTECH_KNOWN_HOSTS }}

      - name: Deploy to server
        run: rsync -avz ./ ${{ secrets.FBDEVTECH_SSH_USER }}@${{ secrets.FBDEVTECH_SSH_HOST }}:/home/developer/api

      - name: Restart the app
        run: ssh ${{ secrets.FBDEVTECH_SSH_USER }}@${{ secrets.FBDEVTECH_SSH_HOST }} 'cd /home/developer/api/ && pm2 restart ecosystem.config.js'

  deploy-devtechnew:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/devtechnew'
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "npm"

      - name: Install dependencies and build
        run: npm ci && npm run build

      - name: Install SSH Key and known_hosts
        uses: shimataro/ssh-key-action@v2.5.1
        with:
          key: ${{ secrets.FBDEVTECHNEW_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.DEVTECHNEW_KNOWN_HOSTS }}

      - name: Deploy to server
        run: rsync -avz ./ ${{ secrets.DEVTECHNEW_SSH_USER }}@${{ secrets.DEVTECHNEW_SSH_SSH_HOST }}:/home/developer/api

      - name: Restart the app
        run: ssh ${{ secrets.DEVTECHNEW_SSH_USER }}@${{ secrets.DEVTECHNEW_SSH_SSH_HOST }} 'cd /home/developer/api/ && pm2 restart ecosystem.config.js'

  deploy-dev2:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev2'
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "npm"

      - name: Install dependencies and build
        run: npm ci && npm run build

      - name: Install SSH Key and known_hosts
        uses: shimataro/ssh-key-action@v2.5.1
        with:
          key: ${{ secrets.FBDEV2_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.FBDEV2_KNOWN_HOSTS }}

      - name: Deploy to server
        run: rsync -avz ./ ${{ secrets.FBDEV2_SSH_USER }}@${{ secrets.FBDEV2_SSH_SSH_HOST }}:/home/developer/api

      - name: Restart the app
        run: ssh ${{ secrets.FBDEV2_SSH_USER }}@${{ secrets.FBDEV2_SSH_SSH_HOST }} 'cd /home/developer/api/ && pm2 restart ecosystem.config.js'

  deploy-fbdemo:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/fbdemo'
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "npm"

      - name: Install dependencies and build
        run: npm ci && npm run build

      - name: Install SSH Key and known_hosts
        uses: shimataro/ssh-key-action@v2.5.1
        with:
          key: ${{ secrets.FBDEMO_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.FBDEMO_KNOWN_HOSTS }}

      - name: Deploy to server
        run: rsync -avz ./ ${{ secrets.FBDEMO_SSH_USER }}@${{ secrets.FBDEMO_SSH_HOST }}:/home/developer/api

      - name: Restart the app
        run: ssh ${{ secrets.FBDEMO_SSH_USER }}@${{ secrets.FBDEMO_SSH_HOST }} 'cd /home/developer/api/ && pm2 restart ecosystem.config.js'

  deploy-fb3:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Atom-F0.3'
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "npm"

      - name: Install dependencies and build
        run: npm ci && npm run build

      - name: Install SSH Key and known_hosts
        uses: shimataro/ssh-key-action@v2.5.1
        with:
          key: ${{ secrets.FB3_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.FB3_KNOWN_HOSTS }}

      - name: Deploy to server
        run: rsync -avz ./ ${{ secrets.FB3_SSH_USER }}@${{ secrets.FB3_SSH_HOST }}:/home/developer/api

      - name: Restart the app
        run: ssh ${{ secrets.FB3_SSH_USER }}@${{ secrets.FB3_SSH_HOST }} 'cd /home/developer/api/ && pm2 restart ecosystem.config.js'

  deploy-fb4:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Atom-F0.4'
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "npm"

      - name: Install dependencies and build
        run: npm ci && npm run build

      - name: Install SSH Key and known_hosts
        uses: shimataro/ssh-key-action@v2.5.1
        with:
          key: ${{ secrets.FB4_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.FB4_KNOWN_HOSTS }}

      - name: Deploy to server
        run: rsync -avz ./ ${{ secrets.FB4_SSH_USER }}@${{ secrets.FB4_SSH_HOST }}:/home/developer/api

      - name: Restart the app
        run: ssh ${{ secrets.FB4_SSH_USER }}@${{ secrets.FB4_SSH_HOST }} 'cd /home/developer/api/ && pm2 restart ecosystem.config.js'

  deploy-fb5:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Atom-F0.5'
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "npm"

      - name: Install dependencies and build
        run: npm ci && npm run build

      - name: Install SSH Key and known_hosts
        uses: shimataro/ssh-key-action@v2.5.1
        with:
          key: ${{ secrets.FB5_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.FB5_KNOWN_HOSTS }}

      - name: Deploy to server
        run: rsync -avz ./ ${{ secrets.FB5_SSH_USER }}@${{ secrets.FB5_SSH_HOST }}:/home/developer/api

      - name: Restart the app
        run: ssh ${{ secrets.FB5_SSH_USER }}@${{ secrets.FB5_SSH_HOST }} 'cd /home/developer/api/ && pm2 restart ecosystem.config.js'



  deploy-prodtech:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prodtech'
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "npm"

      - name: Install dependencies and build
        run: npm ci && npm run build

      - name: Install SSH Key and known_hosts
        uses: shimataro/ssh-key-action@v2.5.1
        with:
          key: ${{ secrets.FBPRODTECH_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.FBPRODTECH_KNOWN_HOSTS }}

      - name: Deploy to server
        run: rsync -avz ./ ${{ secrets.FBPRODTECH_SSH_USER }}@${{ secrets.FBPRODTECH_SSH_HOST }}:/home/developer/api

      - name: Restart the app
        run: ssh ${{ secrets.FBPRODTECH_SSH_USER }}@${{ secrets.FBPRODTECH_SSH_HOST }} 'cd /home/developer/api/ && pm2 restart ecosystem.config.js'
