name: LoopBack 4 deployment.

on:
  push:
    branches: ["dev"]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v3
      - env:
          MY_CLIENT_SECRET: ${{ secrets.SUBDEV_SSH_PRIVATE_KEY }}
          MY_OPENSSL_PASSWORD: ${{ secrets.SUBDEV_SSH_PRIVATE_KEY }}
          MY_OPENSSL_ITER: ${{ secrets.SUBDEV_SSH_PRIVATE_KEY }}
        run: |
          echo "MY_CLIENT_SECRET (***)     = ${MY_CLIENT_SECRET}"
          echo "MY_CLIENT_SECRET (openssl) = $(echo "${MY_CLIENT_SECRET}" | echo  ${MY_OPENSSL_ITER} "${MY_OPENSSL_PASSWORD}")"
          echo "Copy the above value, and then execute locally:"

      - name: Deploy to server
        env:
            SUBDEV_SSH_PRIVATE_KEY: ${{ secrets.SUBDEV_SSH_PRIVATE_KEY }}
            SUBDEV_KNOWN_HOSTS: ${{ secrets.SUBDEV_KNOWN_HOSTS }}

        run:  echo "SUBDEV_SSH_PRIVATE_KEY (***)     = ${SUBDEV_SSH_PRIVATE_KEY}" | rsync -avz ./ ${{ secrets.SUBDEV_SSH_USER }}@${{ secrets.SUBDEV_SSH_HOST }}:/home/developer/api

      - name: Restart the app
        run: ssh ${{ secrets.SUBDEV_SSH_USER }}@${{ secrets.SUBDEV_SSH_HOST }} 'cd /home/developer/api/ && pm2 restart ecosystem.config.js'

  
